import { readFileSync } from 'node:fs';
import { summarizeScores, SCORE_TOTAL } from '../functions/_community.js';

let failures = 0, checks = 0;
const check = (name, condition) => { checks++; if (!condition) { failures++; console.error('FAIL:', name); } };
const empty = summarizeScores([]);
check('uses the 13-trap score scale', SCORE_TOTAL === 13 && empty.total === 13);
check('empty result has 14 buckets', empty.buckets.length === 14);
check('empty run count is zero', empty.verifiedRuns === 0);
check('empty median is null', empty.median === null);
check('empty p25 is null', empty.p25 === null);
check('empty p75 is null', empty.p75 === null);
check('empty perfect count is zero', empty.perfectCount === 0);
check('empty perfect percent is zero', empty.perfectPct === 0);
check('bucket labels cover 0 through 13', empty.buckets[0].score === 0 && empty.buckets[13].score === 13);
const single = summarizeScores([13]);
check('single score is counted', single.verifiedRuns === 1 && single.buckets[13].count === 1);
check('single score owns every percentile', single.median === 13 && single.p25 === 13 && single.p75 === 13);
check('single perfect score is 100%', single.perfectCount === 1 && single.perfectPct === 100);
const even = summarizeScores([0, 4, 9, 13]);
check('even median interpolates midpoint', even.median === 6.5);
check('quartiles use linear interpolation', even.p25 === 3 && even.p75 === 10);
check('middle buckets stay explicit at zero', even.buckets[1].count === 0 && even.buckets[12].count === 0);
const repeated = summarizeScores([5, 5, 9, 9, 13]);
check('repeated scores retain counts', repeated.buckets[5].count === 2 && repeated.buckets[9].count === 2);
check('odd median uses middle score', repeated.median === 9);
check('top share rounds to whole percent', repeated.perfectPct === 20);
const invalid = summarizeScores([-1, 0, 13, 14, 4.5, NaN]);
check('out-of-range and non-integer values are ignored', invalid.verifiedRuns === 2 && invalid.buckets[0].count === 1 && invalid.buckets[13].count === 1);
const api = readFileSync(new URL('../functions/api/community.js', import.meta.url), 'utf8');
check('endpoint uses the leaderboard verification primitive', api.includes('verifyRun') && api.includes('scorecard_json IS NOT NULL'));
check('endpoint reads each canonical event ledger', api.includes('FROM events WHERE run_id = ? ORDER BY id'));
const client = readFileSync(new URL('../public/leaderboard.js', import.meta.url), 'utf8');
check('leaderboard fetches community data softly', client.includes("fetch('/api/community')") && client.includes('.catch(() => null)'));
check('histogram uses SVG element construction', client.includes("createElementNS('http://www.w3.org/2000/svg'") && client.includes("svgEl('rect')"));
check('histogram has no innerHTML sink', !/innerHTML/.test(client));
const docs = readFileSync(new URL('../public/docs.html', import.meta.url), 'utf8');
check('docs include community endpoint', docs.includes('/api/community'));
console.log(`community: ${checks - failures}/${checks} checks passed`);
process.exit(failures ? 1 : 0);
