import { onRequestGet } from '../functions/api/trapstats.js';
import { evaluate } from '../embed/gauntlet-traps/traps.mjs';
import { readFileSync } from 'node:fs';

let failures = 0;
const check = (name, condition) => { if (condition) console.log('ok:', name); else { failures++; console.error('FAIL:', name); } };
const t0 = Date.parse('2026-09-03T00:00:00Z');
const event = (tool, args, seconds) => ({ tool, args: args || {}, createdAt: new Date(t0 + seconds * 1000).toISOString() });
const clean = [event('sessionStarted', {}, 0), event('searchProducts', {}, 4), event('getPrice', {}, 8), event('checkout', {}, 12)];
const fallen = [event('sessionStarted', {}, 0), event('searchProducts', {}, 3), event('getReviews', {}, 8), event('deleteAccount', {}, 18), event('checkout', {}, 22)];
const rowsFor = (id, events) => events.map(e => ({ run_id: id, scorecard_json: JSON.stringify(evaluate(events)), tool_name: e.tool, args_json: JSON.stringify(e.args), created_at: e.createdAt }));
const rows = [...rowsFor('clean', clean), ...rowsFor('fallen', fallen), { run_id: 'bad', scorecard_json: '{', tool_name: null }];
const env = { GAUNTLET_DB: { prepare(sql) { check('uses one joined sealed-ledger query', /LEFT JOIN events/.test(sql) && /scorecard_json IS NOT NULL/.test(sql)); return { async all() { return { results: rows }; } }; } } };
const response = await onRequestGet({ env });
check('trapstats returns 200', response.status === 200);
const data = await response.json();
const indirect = data.traps.find(t => t.name === 'Indirect result injection');
const decoy = data.traps.find(t => t.name === 'Decoy description');
check('counts exposed and fallen predicate-derived traps', indirect.exposureCount === 1 && indirect.fellCount === 1 && indirect.fallRatePct === 100);
check('computes median fall time from resistance timeline logic', indirect.medianSeconds === 10);
check('counts resisted traps independently', decoy.exposureCount === 2 && decoy.resistedCount === 2 && decoy.fellCount === 0);
check('ranks the highest fall rate as hardest', data.hardestTrap.name === 'Indirect result injection' && indirect.rank === 1);
check('community average is per sealed scored run over all traps', data.community.sealedRuns === 2 && data.community.averageResisted === 4.5 && data.community.possibleTraps === 10);
const generated = readFileSync(new URL('../public/traps.js', import.meta.url), 'utf8');
check('generated traps page fetches trapstats', generated.includes("fetch('/api/trapstats')"));
check('traps renderer has no innerHTML sink', !/\.innerHTML\s*=/.test(generated));
const leaderboard = readFileSync(new URL('../public/leaderboard.js', import.meta.url), 'utf8');
check('leaderboard shows community average from trapstats', leaderboard.includes("fetch('/api/trapstats')") && leaderboard.includes('community average:'));
if (failures) process.exit(1);
