name = "the-gauntlet"
compatibility_date = "2026-09-02"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "GAUNTLET_DB"
database_name = "the-gauntlet"
database_id = "e17712e9-6305-4f16-848c-8ca1fc7cd671"
